#!/usr/bin/env python3
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INSTALL_SCRIPT = (ROOT / "scripts/install.sh").read_text(encoding="utf-8")
OUTPUT = ROOT / "egg-windrose-native-linux.json"


def variable(name, description, env, default, viewable, editable, rules, field_type="text"):
    return {
        "name": name,
        "description": description,
        "env_variable": env,
        "default_value": default,
        "user_viewable": viewable,
        "user_editable": editable,
        "rules": rules,
        "field_type": field_type,
    }


egg = {
    "_comment": "DO NOT EDIT: FILE GENERATED AUTOMATICALLY BY tools/generate_egg.py",
    "meta": {"version": "PTDL_v2", "update_url": None},
    "exported_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    "name": "Windrose Native Linux",
    "author": "1725073+Kalanur@users.noreply.github.com",
    "description": (
        "Runs the official native Linux Windrose dedicated server. The installer extracts "
        "the game payload directly from windroseserver/windroseserver; the runtime image "
        "contains only Pterodactyl compatibility and configuration tooling."
    ),
    "features": [],
    "docker_images": {
        "ghcr.io/kalanur/pterodactyl-windrose-native:latest": (
            "ghcr.io/kalanur/pterodactyl-windrose-native:latest"
        )
    },
    "file_denylist": [],
    "startup": "/usr/local/bin/windrose-start",
    "config": {
        "files": "{}",
        "startup": json.dumps({"done": "Bringing up level for play took"}, indent=4),
        "logs": "{}",
        "stop": "^C",
    },
    "scripts": {
        "installation": {
            "script": INSTALL_SCRIPT,
            "container": "ghcr.io/ptero-eggs/installers:debian",
            "entrypoint": "bash",
        }
    },
    "variables": [
        variable(
            "Server Name",
            "Name shown for this Windrose server.",
            "SERVER_NAME",
            "Pterodactyl Windrose Server",
            True,
            True,
            "required|string|max:40",
        ),
        variable(
            "Invite Code",
            "Optional fixed invite code. Leave empty to preserve the code generated by the server.",
            "INVITE_CODE",
            "",
            True,
            True,
            "nullable|string|min:6|max:32|regex:/^[a-zA-Z0-9]+$/",
        ),
        variable(
            "Server Password",
            "Leave empty to disable password protection.",
            "PASSWORD",
            "",
            True,
            True,
            "nullable|string|max:30",
        ),
        variable(
            "Maximum Players",
            "Maximum number of simultaneous players.",
            "MAX_PLAYER_COUNT",
            "8",
            True,
            True,
            "required|integer|min:1|max:10",
        ),
        variable(
            "Connection Region",
            "Connection Service region. EU also covers North America. Leave empty for automatic selection.",
            "USER_SELECTED_REGION",
            "EU",
            True,
            True,
            "nullable|string|in:EU,SEA,CIS",
        ),
        variable(
            "P2P Proxy Address",
            "Listening address for invite-code/P2P mode. For same-LAN clients this may need the host LAN address.",
            "P2P_PROXY_ADDRESS",
            "127.0.0.1",
            True,
            True,
            "required|ip",
        ),
        variable(
            "Use Direct Connection",
            "Use the primary Pterodactyl allocation directly. The same port must be reachable through TCP and UDP.",
            "USE_DIRECT_CONNECTION",
            "0",
            True,
            True,
            "required|boolean",
        ),
        variable(
            "World Island ID",
            "Optional world folder ID used to select an imported world. Leave empty to preserve the current selection.",
            "WORLD_ISLAND_ID",
            "",
            True,
            True,
            "nullable|string|max:64|regex:/^[A-Za-z0-9_-]+$/",
        ),
        variable(
            "Automatic Corrupt-Save Recovery",
            "Automatically load the latest backup when the active save is detected as broken.",
            "AUTO_LOAD_LATEST_BACKUP_IF_HAS_BROKEN",
            "1",
            True,
            True,
            "required|boolean",
        ),
        variable(
            "Official Image Repository",
            "Official Windrose Docker repository used during installation.",
            "WINDROSE_IMAGE_REPOSITORY",
            "windroseserver/windroseserver",
            False,
            False,
            "required|string|in:windroseserver/windroseserver",
        ),
        variable(
            "Official Image Tag",
            "Official Windrose Docker tag used during installation or reinstall.",
            "WINDROSE_IMAGE_TAG",
            "latest",
            True,
            False,
            "required|string|max:128",
        ),
    ],
}

OUTPUT.write_text(json.dumps(egg, indent=4, ensure_ascii=False) + "\n", encoding="utf-8")
print(OUTPUT)
